/**
 * Default Subscription Plans
 * Used as fallback when database tables aren't created yet
 * @module billing/constants
 */

import type { SubscriptionPlan, CreditPackage } from '../types';

export const DEFAULT_PLANS: SubscriptionPlan[] = [
  {
    id: 'free-plan',
    name: 'Free',
    slug: 'free',
    stripe_product_id: 'prod_TZFhcJ51ZBCqn5',
    stripe_price_id_monthly: null,
    stripe_price_id_yearly: null,
    monthly_price: 0,
    yearly_price: 0,
    monthly_credits: 0,
    free_bookings_per_month: -1, // Unlimited
    free_ai_conversations_per_month: 0,
    transaction_fee_percent: 3.9,
    description: 'Perfect for getting started with booking management',
    is_active: true,
    is_popular: false,
    display_order: 1,
    features: [
      'Unlimited bookings management',
      '3.9% transaction fee',
      '3 active games/rooms',
      '3 staff members',
      'Basic booking widget',
      'Standard waivers',
      'Email support',
      'Basic reports',
    ],
    limits: { games: 3, staff: 3, widgets: 1, api_access: false },
  },
  {
    id: 'starter-plan',
    name: 'Starter',
    slug: 'starter',
    stripe_product_id: 'prod_TZFh2Ef5vF308i',
    stripe_price_id_monthly: 'price_1Sc7CVFajiBPZ08x83pCUGwV',
    stripe_price_id_yearly: 'price_1Sc7CWFajiBPZ08xfmDqFJy4',
    monthly_price: 49,
    yearly_price: 470,
    monthly_credits: 100,
    free_bookings_per_month: 30,
    free_ai_conversations_per_month: 30,
    transaction_fee_percent: 0,
    description: 'Perfect for small escape room businesses',
    is_active: true,
    is_popular: false,
    display_order: 2,
    features: [
      'Up to 30 free bookings/month',
      'Up to 30 free AI conversations/month',
      '100 credits/month included',
      '0% transaction fee',
      '5 active games/rooms',
      '5 staff members',
      '3 widget templates',
      'Standard waivers',
      'Email support',
      'Basic reports',
    ],
    limits: { games: 5, staff: 5, widgets: 3, api_access: false },
  },
  {
    id: 'professional-plan',
    name: 'Professional',
    slug: 'professional',
    stripe_product_id: 'prod_TZFhTtqzY0xrjy',
    stripe_price_id_monthly: 'price_1Sc7CWFajiBPZ08xzjay7l8B',
    stripe_price_id_yearly: 'price_1Sc7CXFajiBPZ08x0wJh0wwQ',
    monthly_price: 99,
    yearly_price: 950,
    monthly_credits: 200,
    free_bookings_per_month: 60,
    free_ai_conversations_per_month: 60,
    transaction_fee_percent: 0,
    description: 'Advanced features for growing businesses',
    is_active: true,
    is_popular: true,
    display_order: 3,
    features: [
      'Up to 60 free bookings/month',
      'Up to 60 free AI conversations/month',
      '200 credits/month included',
      '0% transaction fee',
      '15 active games/rooms',
      '25 staff members',
      'All 8 widget templates',
      'Custom waiver templates',
      'Advanced AI agents',
      'Priority support',
      'Advanced analytics',
    ],
    limits: { games: 15, staff: 25, widgets: 8, api_access: false },
  },
  {
    id: 'enterprise-plan',
    name: 'Enterprise',
    slug: 'enterprise',
    stripe_product_id: 'prod_TZFhHhLXXUBeJx',
    stripe_price_id_monthly: null,
    stripe_price_id_yearly: null,
    monthly_price: 0,
    yearly_price: 0,
    monthly_credits: 0,
    free_bookings_per_month: -1,
    free_ai_conversations_per_month: -1,
    transaction_fee_percent: 0,
    description: 'Complete solution for established chains',
    is_active: true,
    is_popular: false,
    display_order: 4,
    features: [
      'Unlimited bookings',
      'Unlimited AI conversations',
      'Custom credit allocation',
      'Unlimited games/rooms',
      'Unlimited staff members',
      'All widgets with customization',
      'Custom waiver templates + legal review',
      'All AI agents',
      'Dedicated account manager',
      '24/7 phone support',
      'API access',
      'White-label options',
    ],
    limits: { games: -1, staff: -1, widgets: -1, api_access: true },
  },
];

export const DEFAULT_CREDIT_PACKAGES: CreditPackage[] = [
  {
    id: 'credits-small',
    name: 'Small',
    credits: 100,
    price: 9.99,
    stripe_product_id: 'prod_TZFi5yBNYoIjrr',
    stripe_price_id: 'price_1Sc7CkFajiBPZ08xXo6nANOw',
    is_active: true,
    display_order: 1,
  },
  {
    id: 'credits-medium',
    name: 'Medium',
    credits: 250,
    price: 19.99,
    stripe_product_id: 'prod_TZFi1GEaZ6vOQ8',
    stripe_price_id: 'price_1Sc7ClFajiBPZ08xGJuucb5O',
    is_active: true,
    display_order: 2,
  },
  {
    id: 'credits-large',
    name: 'Large',
    credits: 500,
    price: 34.99,
    stripe_product_id: 'prod_TZFidQiJ4jE6JA',
    stripe_price_id: 'price_1Sc7CmFajiBPZ08xRJ3bnHVh',
    is_active: true,
    display_order: 3,
  },
  {
    id: 'credits-xlarge',
    name: 'XLarge',
    credits: 1000,
    price: 59.99,
    stripe_product_id: 'prod_TZFilzXL8BY0iW',
    stripe_price_id: 'price_1Sc7CnFajiBPZ08xorPw7h4x',
    is_active: true,
    display_order: 4,
  },
];
